### ISSUE TITLE
Once stop the task I cannot resume

### ISSUE THREAD

**Issue by teaguexiao** [awslabs/aws-data-replication-hub#5]
Once a task is stopped there's no resume button, I can only recreate another task and input all parameters again which takes some time.

A stop/resume function should be added.

**Comment by JoeShi** [comment]
Thank you for reaching us. 

Currently, once the task has entered `STOPPED` state, the underlying infrastructure will be destroyed in order to save cost. We don't want to keep the task infrastructure

How do you think about this?
1. We add an option to **clone** the task
2. The **clone** action will copy the parameters to another task creation page
3. You can modify the parameters or simply create **Next** button to confirm your inputs


p.s. When you create a new task with the same parameters, objects which have been replicated will not be replicated again.

**Comment by teaguexiao** [comment]
this sounds good.

**Comment by JoeShi** [comment]
OK. We will add this in the next release

**Comment by JoeShi** [comment]
Released. Please reopen this ticket if needed.
